apiVersion: v1
kind: Service
metadata:
  name: tapngo-service
spec:
  selector:
    app: tapngo
  type: NodePort
  ports:
    - protocol: TCP
      port: 80            
      targetPort: 8080   
      nodePort: 31245
